version: '3.4'

services:
  webapiminimal:
    image: ${DOCKER_REGISTRY-}webapiminimal
    build:
      context: .
      dockerfile: WebApiMinimal/Dockerfile
#  ms-sql-server:  
#   image: 'microsoft/mssql-server-linux:2017-latest'  
#   ports:  
#      - '1401:1433'  
#   environment:  
#      SA_PASSWORD: Pa$$w0rd2019  
#      ACCEPT_EULA: Y  
#      MSSQL_PID: Developer  
#   colour-api:  
#   build:  
#      context: ColourAPI  
#      dockerfile: Dockerfile  
#    environment:  
#- ASPNETCORE_ENVIRONMENT=Development  
#- ConnectionStrings_DefaultConnection=Server=localhost,1401;database=Colours;User Id=sa;Password=Pa$$w0rd2019  
#ports:  
#- '8080:80'  
#depends_on:  
#- ms-sql-server    
